apiVersion: apps/v1
kind: Deployment
metadata:
  name: nstam
spec:
  replicas: 2
  revisionHistoryLimit: 1
  template:
    spec:
      containers:
        - name: nstam
          image: nstam
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 32Mi
          ports:
            - name: web
              containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: web
            initialDelaySeconds: 5
          livenessProbe:
            tcpSocket:
              port: web
            initialDelaySeconds: 5
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              readOnly: true
              name: nginx-conf
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: default.conf
