apiVersion: apps/v1
kind: Deployment
metadata:
  name: nstam
spec:
  replicas: 2
  revisionHistoryLimit: 1
  template:
    spec:
      containers:
        - name: nstam
          image: nstam
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 32Mi
          ports:
            - containerPort: 80
          readinessProbe:
            tcpSocket:
              port: 80
            failureThreshold: 2
            initialDelaySeconds: 10
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            tcpSocket:
              port: 80
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 2
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              readOnly: true
              name: nginx-conf
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: default.conf
