apiVersion: apps/v1
kind: Deployment
metadata:
  name: nstam
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    spec:
      containers:
        - name: nstam
          image: nstam
          command: ["nginx", "-g", "daemon off;"]
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 20m
              memory: 16Mi
            limits:
              memory: 16Mi
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: web
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: web
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 5
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              readOnly: true
              name: nginx-conf
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: default.conf
