name: build

on:
  push:
    branches:
      - "!master"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: docker/setup-buildx-action@v1.0.3

      - uses: docker/build-push-action@v2.2.1
        with:
          context: .
          file: ./Dockerfile
          tags: nickstamat/nstam:${{ github.sha }}
          push: false
          build-args: COMMIT_SHA=${{ github.sha }}
