name: build-deploy

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: docker/setup-buildx-action@v1.0.3

      - uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - uses: docker/build-push-action@v2.2.1
        with:
          context: .
          file: ./Dockerfile
          tags: nickstamat/nstam:${{ github.sha }}
          push: true
          build-args: COMMIT_SHA=${{ github.sha }}

      - uses: actions/checkout@v2.3.4
        with:
          repository: nickstamat/k8s-var-services
          token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          path: _k8s

      - run: |
          rm -f $GITHUB_WORKSPACE/_k8s/k8s/nstam/*
          envsubst <$GITHUB_WORKSPACE/ops/k8s/production/kustomization.yml >file.tmp && mv file.tmp $GITHUB_WORKSPACE/ops/k8s/production/kustomization.yml
          kubectl kustomize ops/k8s/production/ > all-in-one.yml
          cp all-in-one.yml $GITHUB_WORKSPACE/_k8s/k8s/nstam/

      - run: |
          cd $GITHUB_WORKSPACE/_k8s/
          git config --global user.email "stamatopoulosnikos@gmail.com"
          git config --global user.name "GitHub Actions [nstam.gr]"
          git add -v k8s/nstam/
          git commit -m "Update k8s/nstam"
          git push origin master
