name: ci

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          docker build . -t nickstamat/nstam:${{ github.sha }}
          docker push nickstamat/nstam:${{ github.sha }}
        env:
          DOCKER_BUILDKIT: '1'
